export * from '../pages/pages/Home'
export * from '../pages/pages/Header'
export * from '../pages/pages/HomeCarousel'
export * from '../pages/pages/Footer'
export * from '../pages/pages/TeachersNativos'
export * from '../pages/pages/Faqs'
export * from '../pages/pages/Testimonios'